version: '3.8'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    environment:
      - WG_HOST=$WG_HOST
      - PASSWORD=$PASSWORD
      - WG_DEFAULT_ADDRESS=$WG_DEFAULT_ADDRESS
      - WG_DEFAULT_DNS=$WG_DEFAULT_DNS
      - WG_DEVICE=eth1
    ports:
      - '51821:51821/tcp'
      - '51820:51820/udp'
    volumes:
      - '~/.wg-easy:/etc/wireguard'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:51821"]
      interval: 2s
      timeout: 10s
      retries: 15
